### ISSUE TITLE
Serious naming issues

### ISSUE THREAD

**Issue by Coderog** [LiuChenxuan/RoboMasterBattleGround#1]
Docs/**Official**
Docs/Offitial/RM2018机甲大师赛比赛规则手册V1.2.1.0(4月4日).pdf
Docs/Offitial/RoboMaster 2018 Rules Manual V1.1.pdf

btw I do **not** think mixing languages is any good...

**Comment by LiuChenxuan** [comment]
Thank you for being our **Names Inspector**, I have already corrected them.
